package com.example.chinyao.mow.mowdigest.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by chinyao on 7/30/2016.
 */
public class MowdigestMedia {
    List<MowdigestImage> mediaMetadata;

    // public constructor is necessary for collections
    public MowdigestMedia() {
        mediaMetadata = new ArrayList<>();
    }

    // the following is generated by Android Studio

    public List<MowdigestImage> getMediaMetadata() {
        return mediaMetadata;
    }
}
