package com.example.chinyao.mow.mowdigest.model;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by chinyao on 7/30/2016.
 */
public class MowdigestArticleSearch {
    List<MowdigestNews> results;

    // public constructor is necessary for collections
    public MowdigestArticleSearch() {
        results = new ArrayList<>();
    }

    public static MowdigestArticleSearch parseJSON(String response) {
        // This is not a stable solution.
        // Instead, use default with @SerializedName("_some-field-name")
        // LOWER_CASE_WITH_DASHES translate "_some-field-name" to "_someFieldName"
        // GsonBuilder gsonBuilder = new GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_DASHES);

        GsonBuilder gsonBuilder = new GsonBuilder();
        // register type adapters here, specify field naming policy, etc.
        Gson gson = gsonBuilder.create();
        MowdigestArticleSearch theSearch = gson.fromJson(response, MowdigestArticleSearch.class);
        return theSearch;
    }

    // the following is generated by Android Studio

    public List<MowdigestNews> getResults() {
        return results;
    }
}
