package com.example.chinyao.mow.mowdigest.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by chinyao on 7/29/2016.
 */
public class MowdigestNews {
    String url;
    String title;
    String section;
    String published_date;
    List<MowdigestMedia> media;

    // public constructor is necessary for collections
    public MowdigestNews() {
        media = new ArrayList<>();
    }

    public static List<MowdigestNews> debug() {
        ArrayList<MowdigestNews> output = new ArrayList<>();
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        return output;
    }

    // the following is generated by Android Studio

    public List<MowdigestMedia> getMedia() {
        return media;
    }

    public String getPublished_date() {
        return published_date;
    }

    public String getSection() {
        return section;
    }

    public String getTitle() {
        return title;
    }

    public String getUrl() {
        return url;
    }
}
