package com.example.chinyao.mow.mowdigest.model;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * Created by chinyao on 7/31/2016.
 */
public class MowdigestSearchResult {
    MowdigestResponse response;

    // public constructor is necessary for collections
    public MowdigestSearchResult() {
        response = new MowdigestResponse();
    }

    public static MowdigestSearchResult parseJSON(String response) {
        GsonBuilder gsonBuilder = new GsonBuilder();
        Gson gson = gsonBuilder.create();
        MowdigestSearchResult theSearch = gson.fromJson(response, MowdigestSearchResult.class);
        return theSearch;
    }

    // the following is generated by Android Studio

    public MowdigestResponse getResponse() {
        return response;
    }
}
