package com.example.chinyao.mow.mowdigest.model;

/**
 * Created by chinyao on 7/30/2016.
 */
public class MowdigestImage {
    String url;
    String format;

    // the following is generated by Android Studio

    public String getFormat() {
        return format;
    }

    public String getUrl() {
        return url;
    }
}
