package com.example.chinyao.mow.mowdigest.model;

import android.annotation.TargetApi;
import android.os.Build;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/**
 * Created by chinyao on 7/29/2016.
 */
public class MowdigestPopularNews {
    String url;
    String title;
    String section;
    String published_date;
    @SerializedName("abstract")
    String abstractString;
    List<MowdigestMedia> media;

    // boolean default is false
    // Boolean default is null
    boolean mowdigestFullSpan;

    public static List<MowdigestPopularNews> debug() {
        ArrayList<MowdigestPopularNews> output = new ArrayList<>();
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        output.add(null);
        return output;
    }

    @TargetApi(Build.VERSION_CODES.N)
    public static MowdigestPopularNews fromSearchNews(MowdigestSearchNews theSearchNews) {
        MowdigestPopularNews thePopularNews = new MowdigestPopularNews();
        thePopularNews.url = theSearchNews.getWeb_url();
        thePopularNews.title = theSearchNews.getSnippet();
        thePopularNews.section = theSearchNews.getSection_name();
        thePopularNews.published_date = theSearchNews.getPub_date().substring(0, 10);
        thePopularNews.abstractString = "";
        thePopularNews.media = new ArrayList<>();
        MowdigestMedia theMedia = new MowdigestMedia();
        theMedia.mediaMetadata = theSearchNews.getMultimedia();
        Collections.sort(theMedia.mediaMetadata, new Comparator<MowdigestImage>() {
            @Override
            public int compare(MowdigestImage mowdigestImage, MowdigestImage t1) {
                int mowdigestImageHeight = Integer.parseInt(mowdigestImage.getHeight());
                int t1Height = Integer.parseInt(t1.getHeight());
                if (mowdigestImageHeight < t1Height) {
                    return 1; // from large to small
                }
                else {
                    return -1;
                }
            }
        });
        for (MowdigestImage theImage : theMedia.mediaMetadata) {
            theImage.url = "https://static01.nyt.com/" + theImage.url;
        }
        thePopularNews.media.add(theMedia);
        return thePopularNews;
    }

    // the following is generated by Android Studio

    public void setMowdigestFullSpan(boolean value) {
        mowdigestFullSpan = value;
    }

    public boolean getMowdigestFullSpan() {
        return mowdigestFullSpan;
    }

    public List<MowdigestMedia> getMedia() {
        return media;
    }

    public String getAbstractString() {
        return abstractString;
    }

    public String getPublished_date() {
        return published_date;
    }

    public String getSection() {
        return section;
    }

    public String getTitle() {
        return title;
    }

    public String getUrl() {
        return url;
    }
}
